name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          libsdl2-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libgtk2.0-dev \
          libgtkglext1-dev \
          libmxml-dev \
          liblua5.3-dev \
          libogg-dev \
          libvorbis-dev \
          libjpeg-dev \
          libpng-dev \
          libcurl4-openssl-dev \
          libxvidcore-dev \
          libtheora-dev \
          libgtest-dev \
          libopenal-dev \
          googletest

    - name: Build GTest (required on Ubuntu)
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Set up ccache in PATH
      run: echo "/usr/lib/ccache" >> $GITHUB_PATH

    - name: Restore ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ runner.os }}-

    - name: Configure
      run: |
        ./configure --disable-uforadiant CC="gcc" CXX="g++"

    - name: Build ufo2map first
      run: make ufo2map -j$(nproc)
  
    - name: Build
      run: make -j$(nproc)

    - name: Smoke test (headless run)
      run: |
        timeout 20s SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy ./ufo +snd_init 0 +vid_fullscreen 0 +quit

    - name: Run distcheck
      run: make distcheck

    - name: Save test logs if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          tests/test-suite.log
          */_build/sub/tests/test-suite.log
          **/test-suite.log
          config.log
